### ISSUE TITLE
Number of memories shown in a collection's page is not correct

### ISSUE THREAD

**Issue by skulltech** [SkullTech/kumbu-functional-test-suite#1]
The number of memories shown in a collection's page is not correct, i.e it's not equal to the number of tiles. For example, in the pic below, the number shown is 63, whereas the actual number should be 70. `Test S001` is failing because of this. 

![capture-memories](https://user-images.githubusercontent.com/16862545/32992895-8d62923c-cd76-11e7-8a68-cb41cdce335a.PNG)

**Comment by motdiem** [comment]
You're correct - so the test fails for a good reason. It's not a bug in testing, it's a bug in the product. Once the bug is fixed the test should pass :-)

**Comment by skulltech** [comment]
Closing.
