### ISSUE TITLE
The sort-by option in the memories tab is not working as intented

### ISSUE THREAD

**Issue by skulltech** [SkullTech/kumbu-functional-test-suite#2]
Upon selecting `Sort by title`, it doesn't do so, the sort order doesn't change. `Test M002` is failing because of this.

**Comment by motdiem** [comment]
It looks to be working fine for me on the server. I'll run the test tomorrow morning to be sure (see http://cl.getkumbu.com/1T2W2p0n1z12 )

**Comment by skulltech** [comment]
I tried with both Firefox and Chrome but it was same for both. I will try once again, let me know if you ran the test-suite or not.

**Comment by skulltech** [comment]
Closing.
