### ISSUE TITLE
Selection overlay of the memories tiles not working properly on all platforms

### ISSUE THREAD

**Issue by skulltech** [SkullTech/kumbu-functional-test-suite#3]
The circular selection overlay at the top-left corner of a memory tab, clicking which should select that memory for further action (such as deletion), is not working properly on all platforms. 

- __On `Firefox`__ the overlay is shown and changes color to green upon mouse-hover, but is not clickable.
- __On `Chrome`__ On the regular version it works perfectly. But while operating it through `webdriver`, such as in the case of this test-suite, the overlay doesn't show up at all.

**Comment by motdiem** [comment]
Good catch on Firefox. 
On chrome, how do you suggest we do this ? Would it be possible to assume the item is selected, or just trigger the javascript to do so (I've had issues with overlays before, the sometimes disappear when webdriver updates...)

**Comment by skulltech** [comment]
I think triggering the javascript for this would be a good option. Although we'll be bypassing the frontend that way, we able to test the backend functionality at least. :)

**Comment by skulltech** [comment]
Closing.
